os: osx
osx_image: xcode11
language: node_js
node_js: lts/*

cache: yarn

addons:
  chrome: stable

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn run electron:dist; fi

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: dist_gh_pages
    on:
      repo: dtom90/Produc-dev
      branch: master
