if: branch = master

os: osx
osx_image: xcode11

language: node_js
node_js: lts/*

cache: yarn

script: yarn run gh_pages:build && cp -R .circleci dist_gh_pages && yarn run electron:dist

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: dist_gh_pages
    on:
      repo: dtom90/DevTrack
      branch: master
