version: 2

jobs:
  test:
    docker:
      - image: docker:stable
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build test Docker image
          command: |
            docker build \
                   -f docker/Dockerfile.dev \
                   -t devtrack-test \
                   .
      - run:
          name: Run packages audit, lint, and unit tests
          command: |
            docker run -it \
                   devtrack-test \
                   sh -c 'yarn audit:packages && yarn run lint && yarn run test:unit'
      - run:
          name: Build production Docker image
          command: |
            docker build \
                   -f docker/Dockerfile.prod \
                   -t devtrack-prod \
                   .
      - run:
          name: Run production Docker container
          command: |
            docker run -it --rm \
                   -p 8080:80 \
                   --name devtrack-prod \
                   devtrack-prod
          background: true
      - run:
          name: Build TestCafé image
          command: |
            docker build \
                   -f docker/Dockerfile.testcafe \
                   -t devtrack-testcafe \
                   .
      - run:
          name: Run TestCafé against production container
          command: |
            docker run -it --rm \
                   --net="host" \
                   devtrack-testcafe chromium:headless /tests -c 4 --selector-timeout 3000
      - run:
          name: Stop production Docker contianer
          command: docker stop devtrack-prod
  build-web:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "27:7d:a1:a0:dc:5a:30:f1:47:74:a6:50:af:6e:59:2d"
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build \
                   -f docker/gh-pages.dockerfile \
                   -t devtrack-ghpages .
      - run:
          name: Build GitHub Pages
          command: |
            docker run -it --rm \
                   -v `pwd`:/app -w /app \
                   devtrack-ghpages
      - run:
          name: Publish to GitHub Pages
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use stable
            npm install -g gh-pages@2.1.1
            git config user.email "dtom90@users.noreply.github.com"
            git config user.name "David Thomason"
            gh-pages --dist dist_gh_pages
  build-electron:
    macos:
      xcode: 11.5.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build and release publish Electron app
          command: yarn run electron:release

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
  deploy:
    jobs:
      - build-web:
          filters:
            branches:
              only:
                - master
      - build-electron